server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://39.101.165.196:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'