server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: 39.101.165.196:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8858
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
        #client-ip: 192.168.110.213

management:
  endpoints:
    web:
      exposure:
        include: '*'
